database:
  mysql:
    enabled: true
    host: 'localhost'
    port: 3306
    database: 'bwreplay'
    username: 'root'
    password: '12345'
    ssl: false
    verify-certificate: true
    max-lifetime: 1800
    pool-size: 10
  postgresql:
    enabled: false
    host: 'localhost'
    port: 25567
    database: 'bwreplay'
    username: 'root'
    password: '12345'
    ssl: false
    verify-certificate: true
    max-lifetime: 1800
    pool-size: 10