server-mode: 'none'

proxy-mode:
  enabled: false
  lobby:
    enabled: true
    server-name: 'lobby1'
    playing-servers:
      - 'replayServer1'
      - 'replayServer2'
      - 'replayServer3'

debug: false

recording-settings:
  player-tabPrefix: '%luckperms_prefix%'
  player-tabSuffix: '%luckperms_suffix%'
  player-tagPrefix: '%luckperms_prefix%'
  player-tagSuffix: '%luckperms_suffix%'